name: Build HeadLock V2 Premium

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Check Gradle
        run: ./gradlew --version

      - name: Clean project
        run: ./gradlew clean --stacktrace --no-daemon

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Find APK
        run: |
          echo "===== APK FILES ====="
          find app/build/outputs -type f -name "*.apk" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: HeadLock-V2-Premium-APK
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
